server:
  port: 8001

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8001-hystrixx
    prefer-ip-address: true

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.scau.zifeng.entities    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/*.xml                       # mapper映射文件

spring:
  application:
    name: propertymanagement-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01?serverTimezone=GMT     # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间


info:
  app.name: zifeng-propertymanagement
  company.name: www.scau.zifeng.com
  build.artifactId: propertymanagement-provider-dept-hystrixx-8001
  build.version: 1.0-SNAPSHOT