server:
  port: 7664


#eureka:
#  client: #客户端注册进eureka服务列表内
#    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#  instance:
#    instance-id: microservicecloud-frontcloud7664
#    prefer-ip-address: true


spring:
#  application:
#    name: propertymanagement-frontcloud
  thymeleaf:
    cache: false
    encoding: UTF-8
    content-type: text/html
    mode: LEGACYHTML5
