server:
  port: 5201

feign:
  httpclient:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-repaircloud5201
    prefer-ip-address: true

spring:
  application:
    name: propertymanagement-repaircloud-consumer
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 30000



info:
  app.name: zifeng-propertymanagement
  company.name: www.scau.zifeng.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$